name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Stable Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run cargo check
        run: |
          cargo check --verbose;
          cargo check --features small-vec --verbose;
      - name: Run tests
        run: |
          cargo test --verbose;
          cargo test --features small-vec --verbose;
  test-nightly:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Install Nightly Rust Toolchain
          uses: dtolnay/rust-toolchain@nightly
          with:
            components: miri
        - name: Run cargo check
          run: |
            cargo check --verbose;
            cargo check --features small-vec --verbose;
        - name: Run tests
          run: |
            cargo test --verbose;
            cargo test --features small-vec --verbose;
        - name: Run tests under Miri
          run: |
            cargo miri test --verbose;
            cargo miri test --features small-vec --verbose;
