name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy, miri
      - name: Run cargo check
        run: |
          cargo check --verbose;
          cargo check --features small-vec --verbose;
          cargo check --features thin-segments --verbose;
          cargo check --features small-vec --features thin-segments --verbose;
      - name: Run tests
        run: |
          cargo test --verbose;
          cargo test --features small-vec --verbose;
          cargo test --features thin-segments --verbose;
          cargo test --features small-vec --features thin-segments --verbose;
          cargo miri test --verbose;
